import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner/banner'
import NavBar from '../components/nav/navbar'
import Card from '../components/card/card'
import {motion} from "framer-motion"
import SectionCards from "../components/card/section-cards"
import Footer from "../components/footer/footer"
import Why from "../components/whycomponent/why"
import Link from 'next/link'

export default function Home() {
  const serviceTitle = [
    {
    title:"Respite Short Say Accomodation",
    text:"In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used",
    imgUrl:"/static/short-stay.jpg",
    link:"/respite-short-stay"
  },
  {
    title:"Recovery Accomodation",
    text:"In publishing and graphic design, Lorem ipsum is a ommonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used",
    imgUrl:"/static/recovery-accomodation.webp",
    link:"/recovery-accommodation"
  },
{
  title: "Community Participation Access",
  text:"In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the  without relying on meaningful content. Lorem ipsum may be used",
    imgUrl:"/static/community-participation.png",
    link:"/community-participation"
},
{
  title: "Supported Independent Living",
  text:"In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the  without relying on meaningful content. Lorem ipsum may be used",
    imgUrl:"/static/sil.jpg",
    link:"/sil"
},
{
  title: "Psychosocial Recovery Coach",
  text:"In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the  without relying on meaningful content. Lorem ipsum may be used",
    imgUrl:"/static/recovert-coach.webp",
    link:"/psychosocial-recovery-coach"
},
];




  return (
    <div className={styles.container}>
      <Head>
        <title>Utmost Services WA</title> 
        <meta name="Utmost Services WA" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      


<NavBar />

<Banner />
<section className={styles.cardGrid}>
  <h1>Our Story</h1>
  <div className={styles.gridTemplateOne}>
    <article className={styles.cardArticle}>
      <motion.div className={styles.cardContent}
      whileHover={{ scale: 1.1 }}>
      <div className={styles.cardImageContainer}>
        <div className={styles.parallax}>
  <Card  imgUrl="/static/about-us.jpg" size="large"/> 
      </div>
      </div>
      <div className={styles.cardTextContainer}>
<span className={styles.overlay}></span>
  <div className={styles.cardTextWrap}>
   <h2 className={styles.cardTitle}>Our history</h2> 
   <p className={styles.classText}>
    lorem lorem 
    lorem lorem 
    lorem lorem 
    lorem lorem  
   </p>
  </div>

      </div>
      </motion.div>
    </article>
    <article className={styles.cardArticle}>
    <motion.div className={styles.cardContent}   whileHover={{ scale: 1.1 }}>
      <div className={styles.cardImageContainer}>
  <Card  imgUrl="/static/contact.jpeg" size="large"/> 
      </div>
      <div className={styles.cardTextContainer}>
      <span className={styles.overlay}></span>
  <div className={styles.cardTextWrap}>
   <h2 className={styles.cardTitle}>Contact Us</h2> 
   <p className={styles.classText}>
    lorem lorem 
    lorem lorem 
    lorem lorem 
    lorem loremnyo
   </p>
  </div>
      </div>
      </motion.div>
    </article>
  

</div></section>
<div className={styles.sectionWrapper}>

  <h1 className={styles.service}>Services</h1>
  {serviceTitle.map((x)=>{
  console.log({x})
  return(
    <SectionCards  title ={x.title} text={x.text} imgUrl={x.imgUrl} link={x.link} />

  )
})}


    </div>

    <Why/>
<Footer/>
    </div>

    
  )
}
